export const CHANGE_TITLE_EDITABLE = 'CHANGE_TITLE_EDITABLE';
export const CHANGE_TITLE = 'CHANGE_TITLE';
export const CHANGE_TITLE_SIZE = 'CHANGE_TITLE_SIZE';
export const CHANGE_QUANTITY = 'CHANGE_QUANTITY';
